<?php

    // AT Piwik Admin

    class Admin_AT_Piwik
    extends AT_Piwik {

        /**
        * Network Admin Class
        *
        * Generated by '__construct' method.
        *
        * @var string
        */
        private $network_admin_at_piwik;


        function __construct() {

            if (is_network_admin()) {

                $this->network_admin_at_piwik = new Network_Admin_AT_Piwik();

            } else {

                // Single Edit Handler
                add_action( 'admin_action_settings_update_admin_at_piwik', array($this, 'settings_update_Admin_AT_Piwik') );

                // Load Assets
                add_action('admin_menu', array(&$this, 'load_assets_Admin_AT_Piwik'));

            }

        }

        /**
        * Loads Assets.
        * 
        * @return void
        */
        function load_assets_Admin_AT_Piwik() {

            if ( is_admin() ) {

                //this will run when in the WordPress admin
                if (! is_network_admin()) {

                    $this->page_hook = add_menu_page( 'AT Piwik Settings', 'AT Piwik', 'manage_options', 'at-piwik', array(&$this, 'display_settings_Admin_AT_Piwik'));

                }

                add_action('admin_print_scripts-' . $this->page_hook, array(&$this, 'load_admin_scripts_AT_Piwik'));

            }

        }

        /**
        * Handle Settings Update.
        * 
        * @return void
        */        
        function settings_update_Admin_AT_Piwik() {

            $updated = false;

            $is_multisite = is_multisite();

            check_admin_referer( 'at-piwik-edit-settings' );

            $at_piwik_idsite = isset($_POST['at_piwik_idsite']) ? sanitize_text_field($_POST['at_piwik_idsite']) : false;

            $at_piwik_active = isset($_POST['at_piwik_active']) ? 1 : 0;

            $at_piwik_admin_override = isset($_POST['at_piwik_admin_override']) ? 1 : 0;

            $at_piwik_admin_tracking_code = empty($_POST['at_piwik_admin_tracking_code']) ? false : wp_unslash($_POST['at_piwik_admin_tracking_code']);

            $at_piwik_admin_tracking_url = empty($_POST['at_piwik_admin_tracking_url']) ? false : esc_url($_POST['at_piwik_admin_tracking_url']);
            
            $at_piwik_admin_track_admin = isset($_POST['at_piwik_admin_track_admin']) ? 1 : 0;

            if ( $at_piwik_idsite || ! $at_piwik_active) {

                $updated = true;

                update_option('at_piwik_idsite', $at_piwik_idsite);

                update_option('at_piwik_active', $at_piwik_active);

                update_option('at_piwik_last_update', time());
                
                update_option('at_piwik_admin_track_admin', $at_piwik_admin_track_admin);

                if ($is_multisite)

                    update_option('at_piwik_admin_override', $at_piwik_admin_override);

                if ($at_piwik_admin_override || ! $is_multisite) {

                    if ($at_piwik_admin_tracking_code) {

                        update_option('at_piwik_admin_tracking_code', $at_piwik_admin_tracking_code);

                    } else {
                        
                        delete_option('at_piwik_admin_tracking_code');
                        
                    }
                    
                    if ($at_piwik_admin_tracking_url) {

                        update_option('at_piwik_admin_tracking_url', $at_piwik_admin_tracking_url);

                    } else {

                        $updated = false;

                        update_option('at_piwik_active', 0);

                    }

                } else {

                    update_option('at_piwik_admin_tracking_code', false);

                    update_option('at_piwik_admin_tracking_url', false);

                }

            }

            wp_redirect( add_query_arg( array( 'update' => $updated ? 'updated' : 'failed' ), admin_url( 'admin.php?page=at-piwik') ) );

            exit;
        }

        /**
        * Registers the Blog Admin Page.
        * 
        * @return void
        */        
        function display_settings_Admin_AT_Piwik() {

            $unauthorized = false;

            if ( ! current_user_can( 'manage_options' ) )
                $unauthorized = __( 'You do not have sufficient permissions to edit these settings.' );

            if ($unauthorized) {

                echo "<p>{$unauthorized}</p>\n";

                return;

            }

            $is_multisite = is_multisite();

            $at_piwik_network_admin_tracking_url = $is_multisite ? get_site_option('at_piwik_network_admin_tracking_url', false) : false;

            $at_piwik_network_admin_tracking_code = $is_multisite ? get_site_option('at_piwik_network_admin_tracking_code', false) : false;

            $at_piwik_admin_track_admin = get_option('at_piwik_admin_track_admin', false);
            
            $at_piwik_admin_tracking_url = get_option('at_piwik_admin_tracking_url', false);
            
            $at_piwik_admin_tracking_code = get_option('at_piwik_admin_tracking_code', false);
            
            $at_piwik_admin_override = $is_multisite ? get_option('at_piwik_admin_override', false) : true;

            $at_piwik_idsite = get_option('at_piwik_idsite', false);

            $at_piwik_active = get_option('at_piwik_active', false);

            $at_piwik_last_update = get_option('at_piwik_last_update', false);

            $date = 'Y/m/d g:i:s a';

            $tracking_placeholder = esc_attr(file_get_contents( self::$plugin_path . 'public/tracking_template.inc' ));
            
            if ( isset($_GET['update']) ) {

                $messages = array();

                if ( 'updated' == $_GET['update'] )

                    $messages[1] = __('Settings updated.');

                else

                    $messages[0] = __('Settings could not be updated.');

            }

            if ( ! empty( $messages ) ) {

                foreach ( $messages as $status => $msg )

                    echo '<div id="message" class="' . ($status ? 'updated' : 'error') . '"><p>' . $msg . '</p></div>';

            }

        ?>

        <div class="wrap">

            <h2><?php echo __('ArsTropica Piwik Plugin Settings', 'at-piwik'); ?></h2>

            <br />

            <form method="post" action="<?php echo admin_url('admin.php'); ?>">

                <?php wp_nonce_field( 'at-piwik-edit-settings' ); ?>

                <input type="hidden" name="action" value="settings_update_admin_at_piwik" />

                <table class="form-table">

                    <?php if ($is_multisite) : ?>

                        <tr>

                            <th scope="row"><?php _e( 'Override Network Settings' ); ?></th>

                            <td>

                                <input type="checkbox" class="checkbox" name="at_piwik_admin_override" id="at_piwik_admin_override" value="1" style="width: 16px; min-width: 16px;" <?php checked( (bool) $at_piwik_admin_override, true ); ?> />

                            </td>

                        </tr>

                        <?php endif; ?>

                    <tr class="form-field">

                        <th scope="row"><?php _e( 'Blog Tracking Code' ); ?></th>

                        <td>

                            <textarea name="at_piwik_admin_tracking_code" id="at_piwik_admin_tracking_code" class="<?php echo ($at_piwik_admin_override || ! $is_multisite) ? "" : "disabled"; ?>" <?php disabled( (bool) $is_multisite && $at_piwik_admin_override, false); ?> cols="40" rows="10" onclick="this.focus();this.select()" placeholder="<?php echo ($is_multisite ? ($at_piwik_network_admin_tracking_code ?: $tracking_placeholder) : $tracking_placeholder); ?>"><?php echo esc_textarea( $at_piwik_admin_tracking_code ); ?></textarea>

                            <p class="description">Tracking Code. <br /><?php if ($is_multisite) : ?><strong>Do not change this unless you know what you are doing!</strong><?php endif; ?></p>

                        </td>

                    </tr>

                    <tr class="form-field">

                        <th scope="row"><?php _e( 'Piwik Server URL' ) ?></th>

                        <td>

                            <input type="text" name="at_piwik_admin_tracking_url" id="at_piwik_admin_tracking_url" value="<?php echo esc_attr( $at_piwik_admin_tracking_url ); ?>" class="<?php echo ($at_piwik_admin_override || ! $is_multisite) ? "" : "disabled"; ?>" <?php disabled( (bool) $is_multisite && ! $at_piwik_admin_override, true); ?>  size="33" placeholder="<?php echo $is_multisite ? ($at_piwik_network_admin_tracking_url ?: "http(s)://") : "http(s)://"; ?>" />

                            <p class="description">Piwik Server URL. <br /><?php if ($is_multisite) : ?><strong>Do not change this unless you know what you are doing!</strong><?php endif; ?></p>


                        </td>

                    </tr>

                    <tr class="form-field">

                        <th scope="row"><?php _e( 'Piwik Site ID' ) ?></th>

                        <td><input type="text" name="at_piwik_idsite" id="at_piwik_idsite" value="<?php echo $at_piwik_idsite; ?>" size="4" style="width: 50px;" /></td>

                    </tr>

                    <tr>
                        <th scope="row"><?php _e( 'Enable Tracking' ); ?></th>

                        <td>

                            <label><input type="checkbox" name="at_piwik_active" id="at_piwik_active" value="1" <?php checked( (bool) $at_piwik_active && $at_piwik_idsite, true ); ?> <?php disabled( (bool) ($at_piwik_idsite || ($is_multisite && ! $at_piwik_admin_override)), false); ?> />

                            </label><br/>


                        </td>

                    </tr>

                    <tr>
                        <th scope="row"><?php _e( 'Admin Tracking ' ); ?></th>

                        <td>

                            <label><input type="checkbox" id="at_piwik_admin_track_admin" name="at_piwik_admin_track_admin" value="1" <?php checked( (bool) $at_piwik_admin_track_admin, true ); ?> /> <?php _e( 'Enable' ); ?>
                            </label>

                            <p class="description">Track logged in WordPress admins.</p>

                        </td>

                    </tr>

                    <tr class="form-field">

                        <th scope="row"><?php _e( 'Last Updated' ); ?></th>

                        <td>

                            <label><?php echo ( ! $at_piwik_last_update ) ? __( 'Never' ) : mysql2date( $date, date('Y-m-d h:i:s', $at_piwik_last_update) ); ?></label>

                            <input name="at_piwik_last_update" type="hidden" id="at_piwik_last_update" value="<?php echo $at_piwik_last_update ?>" />

                        </td>

                    </tr>

                </table>

                <?php submit_button(); ?>

            </form>

        </div>

        <script type="text/javascript">

            jQuery( document ).ready(function( $ ) {

                <?php if (is_multisite()) : ?>

                    $('#at_piwik_admin_override').on('click', function(e){

                        if ($(this).is(':checked')) {

                            $('#at_piwik_admin_tracking_code').removeAttr("disabled").removeClass("disabled");

                            $('#at_piwik_admin_tracking_url').removeAttr("disabled").removeClass("disabled");
                            
                            if ($('#at_piwik_idsite').val())
                            
                                $('#at_piwik_admin_track_admin').removeAttr("disabled").removeClass("disabled");

                        } else {

                            $('#at_piwik_admin_tracking_code').attr("disabled", "disabled").addClass("disabled");

                            $('#at_piwik_admin_tracking_url').attr("disabled", "disabled").addClass("disabled");
                            
                            $('#at_piwik_admin_track_admin').attr("disabled", "disabled").addClass("disabled");

                        }

                    });

                    <?php endif; ?>

                $('#at_piwik_idsite').on('blur', function(e){

                    if( ! $(this).val() ) {

                        $('#at_piwik_active').addClass('disabled').attr("disabled", "disabled").removeAttr("checked");

                    } else {

                        $('#at_piwik_active').removeClass('disabled').removeAttr("disabled");

                    }

                });

                $('#at_piwik_admin_tracking_code').on("blur", function(e){

                    var _track = $(this).val();

                    var _patt = /piwik\.php\?idsite=(\d+)/gi;

                    if (_patt.test(_track)) {

                        var _idSites = _track.match(_patt);

                        $('#at_piwik_idsite').val(_idSites[0]);

                        $('#at_piwik_active').removeClass('disabled').removeAttr("disabled").attr("checked", true);

                    }

                });

            });

        </script>

        <?php

        }

        /**
        * Load Admin Page Scripts
        * 
        * @param mixed $hook
        */
        function load_admin_scripts_AT_Piwik($hook = false) {

        } // end register_scripts_and_styles



    }

?>
